global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/metrics"

  - job_name: "postgres"
    static_configs:
      - targets: ["localhost:5432"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["localhost:27017"]

  - job_name: "redis"
    static_configs:
      - targets: ["localhost:6379"]
